//
// pango-version-macros.h header binding for the Free Pascal Compiler aka FPC
//
// Binaries and demos available at http://www.djmaster.com/
//

(* Pango - Internationalized text layout and rendering library
 * Copyright (C) 1999 Red Hat Software
 * Copyright (C) 2012 Ryan Lortie, Matthias Clasen and Emmanuele Bassi
 * Copyright (C) 2016 Chun-wei Fan
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, see <http://www.gnu.org/licenses/>.
 *)

// #ifndef __PANGO_VERSION_H__
// #define __PANGO_VERSION_H__

// #include <pango/pango-features.h>

// #include <glib.h>

//TODO #ifndef _PANGO_EXTERN
//TODO #define _PANGO_EXTERN extern
//TODO #endif

//TODO #define PANGO_AVAILABLE_IN_ALL                   _PANGO_EXTERN

(* XXX: Every new stable minor release bump should add a macro here *)

(**
 * PANGO_VERSION_1_2:
 *
 * A macro that evaluates to the 1.2 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_2        (G_ENCODE_VERSION (1, 2))

(**
 * PANGO_VERSION_1_4:
 *
 * A macro that evaluates to the 1.4 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_4        (G_ENCODE_VERSION (1, 4))

(**
 * PANGO_VERSION_1_6:
 *
 * A macro that evaluates to the 1.6 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_6        (G_ENCODE_VERSION (1, 6))

(**
 * PANGO_VERSION_1_8:
 *
 * A macro that evaluates to the 1.8 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_8        (G_ENCODE_VERSION (1, 8))

(**
 * PANGO_VERSION_1_10:
 *
 * A macro that evaluates to the 1.10 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_10       (G_ENCODE_VERSION (1, 10))

(**
 * PANGO_VERSION_1_12:
 *
 * A macro that evaluates to the 1.12 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_12       (G_ENCODE_VERSION (1, 12))

(**
 * PANGO_VERSION_1_14:
 *
 * A macro that evaluates to the 1.14 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_14       (G_ENCODE_VERSION (1, 14))

(**
 * PANGO_VERSION_1_16:
 *
 * A macro that evaluates to the 1.16 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_16       (G_ENCODE_VERSION (1, 16))

(**
 * PANGO_VERSION_1_18:
 *
 * A macro that evaluates to the 1.18 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_18       (G_ENCODE_VERSION (1, 18))

(**
 * PANGO_VERSION_1_20:
 *
 * A macro that evaluates to the 1.20 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_20       (G_ENCODE_VERSION (1, 20))

(**
 * PANGO_VERSION_1_22:
 *
 * A macro that evaluates to the 1.22 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_22       (G_ENCODE_VERSION (1, 22))

(**
 * PANGO_VERSION_1_24:
 *
 * A macro that evaluates to the 1.24 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_24       (G_ENCODE_VERSION (1, 24))

(**
 * PANGO_VERSION_1_26:
 *
 * A macro that evaluates to the 1.26 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_26       (G_ENCODE_VERSION (1, 26))

(**
 * PANGO_VERSION_1_28:
 *
 * A macro that evaluates to the 1.28 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_28       (G_ENCODE_VERSION (1, 28))

(**
 * PANGO_VERSION_1_30:
 *
 * A macro that evaluates to the 1.30 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_30       (G_ENCODE_VERSION (1, 30))

(**
 * PANGO_VERSION_1_32:
 *
 * A macro that evaluates to the 1.32 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_32       (G_ENCODE_VERSION (1, 32))

(**
 * PANGO_VERSION_1_34:
 *
 * A macro that evaluates to the 1.34 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_34       (G_ENCODE_VERSION (1, 34))

(**
 * PANGO_VERSION_1_36:
 *
 * A macro that evaluates to the 1.36 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_36       (G_ENCODE_VERSION (1, 36))

(**
 * PANGO_VERSION_1_38:
 *
 * A macro that evaluates to the 1.38 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_38       (G_ENCODE_VERSION (1, 38))

(**
 * PANGO_VERSION_1_40:
 *
 * A macro that evaluates to the 1.40 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_40       (G_ENCODE_VERSION (1, 40))

(**
 * PANGO_VERSION_1_42:
 *
 * A macro that evaluates to the 2.38 version of Pango, in a format
 * that can be used by the C pre-processor.
 *
 * Since: 1.42
 *)
//TODO #define PANGO_VERSION_1_42       (G_ENCODE_VERSION (1, 42))

(* evaluates to the current stable version; for development cycles,
 * this means the next stable target
 *)
//TODO #if (PANGO_VERSION_MINOR % 2)
//TODO #define PANGO_VERSION_CUR_STABLE         (G_ENCODE_VERSION (PANGO_VERSION_MAJOR, PANGO_VERSION_MINOR + 1))
//TODO #else
//TODO #define PANGO_VERSION_CUR_STABLE         (G_ENCODE_VERSION (PANGO_VERSION_MAJOR, PANGO_VERSION_MINOR))
//TODO #endif

(* evaluates to the previous stable version *)
//TODO #if (PANGO_VERSION_MINOR % 2)
//TODO #define PANGO_VERSION_PREV_STABLE        (G_ENCODE_VERSION (PANGO_VERSION_MAJOR, PANGO_VERSION_MINOR - 1))
//TODO #else
//TODO #define PANGO_VERSION_PREV_STABLE        (G_ENCODE_VERSION (PANGO_VERSION_MAJOR, PANGO_VERSION_MINOR - 2))
//TODO #endif

(**
 * PANGO_VERSION_MIN_REQUIRED:
 *
 * A macro that should be defined by the user prior to including
 * the pango.h header.
 * The definition should be one of the predefined Pango version
 * macros: %PANGO_VERSION_1_2, %PANGO_VERSION_1_4,...
 *
 * This macro defines the earliest version of Pango that the package is
 * required to be able to compile against.
 *
 * If the compiler is configured to warn about the use of deprecated
 * functions, then using functions that were deprecated in version
 * %PANGO_VERSION_MIN_REQUIRED or earlier will cause warnings (but
 * using functions deprecated in later releases will not).
 *
 * Since: 1.42
 *)
(* If the package sets PANGO_VERSION_MIN_REQUIRED to some future
 * PANGO_VERSION_X_Y value that we don't know about, it will compare as
 * 0 in preprocessor tests.
 *)
//TODO #ifndef PANGO_VERSION_MIN_REQUIRED
//TODO # define PANGO_VERSION_MIN_REQUIRED      (PANGO_VERSION_CUR_STABLE)
//TODO #elif PANGO_VERSION_MIN_REQUIRED == 0
//TODO # undef  PANGO_VERSION_MIN_REQUIRED
//TODO # define PANGO_VERSION_MIN_REQUIRED      (PANGO_VERSION_CUR_STABLE + 2)
//TODO #endif

(**
 * PANGO_VERSION_MAX_ALLOWED:
 *
 * A macro that should be defined by the user prior to including
 * the glib.h header.
 * The definition should be one of the predefined Pango version
 * macros: %PANGO_VERSION_1_2, %PANGO_VERSION_1_4,...
 *
 * This macro defines the latest version of the Pango API that the
 * package is allowed to make use of.
 *
 * If the compiler is configured to warn about the use of deprecated
 * functions, then using functions added after version
 * %PANGO_VERSION_MAX_ALLOWED will cause warnings.
 *
 * Unless you are using PANGO_CHECK_VERSION() or the like to compile
 * different code depending on the Pango version, then this should be
 * set to the same value as %PANGO_VERSION_MIN_REQUIRED.
 *
 * Since: 1.42
 *)
//TODO #if !defined (PANGO_VERSION_MAX_ALLOWED) || (PANGO_VERSION_MAX_ALLOWED == 0)
//TODO # undef PANGO_VERSION_MAX_ALLOWED
//TODO # define PANGO_VERSION_MAX_ALLOWED      (PANGO_VERSION_CUR_STABLE)
//TODO #endif

(* sanity checks *)
//TODO #if PANGO_VERSION_MIN_REQUIRED > PANGO_VERSION_CUR_STABLE
//TODO #error "PANGO_VERSION_MIN_REQUIRED must be <= PANGO_VERSION_CUR_STABLE"
//TODO #endif
//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_MIN_REQUIRED
//TODO #error "PANGO_VERSION_MAX_ALLOWED must be >= PANGO_VERSION_MIN_REQUIRED"
//TODO #endif
//TODO #if PANGO_VERSION_MIN_REQUIRED < PANGO_VERSION_1_2
//TODO #error "PANGO_VERSION_MIN_REQUIRED must be >= PANGO_VERSION_1_2"
//TODO #endif

(* These macros are used to mark deprecated functions in Pango headers,
 * and thus have to be exposed in installed headers.
 *)
//TODO #ifdef PANGO_DISABLE_DEPRECATION_WARNINGS
//TODO # define PANGO_DEPRECATED                       _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_FOR(f)                _PANGO_EXTERN
//TODO # define PANGO_UNAVAILABLE(maj,min)             _PANGO_EXTERN
//TODO #else
//TODO # define PANGO_DEPRECATED                       G_DEPRECATED _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_FOR(f)                G_DEPRECATED_FOR(f) _PANGO_EXTERN
//TODO # define PANGO_UNAVAILABLE(maj,min)             G_UNAVAILABLE(maj,min) _PANGO_EXTERN
//TODO #endif

(* XXX: Every new stable minor release should add a set of macros here *)
//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_2
//TODO # define PANGO_DEPRECATED_IN_1_2                PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_2_FOR(f)         PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_2                _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_2_FOR(f)         _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_2
//TODO # define PANGO_AVAILABLE_IN_1_2                 PANGO_UNAVAILABLE(1, 2)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_2                 _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_4
//TODO # define PANGO_DEPRECATED_IN_1_4                PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_4_FOR(f)         PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_4                _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_4_FOR(f)         _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_4
//TODO # define PANGO_AVAILABLE_IN_1_4                 PANGO_UNAVAILABLE(1, 4)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_4                 _PANGO_EXTERN
//TODO #endif


//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_6
//TODO # define PANGO_DEPRECATED_IN_1_6                PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_6_FOR(f)         PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_6                _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_6_FOR(f)         _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_6
//TODO # define PANGO_AVAILABLE_IN_1_6                 PANGO_UNAVAILABLE(1, 6)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_6                 _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_8
//TODO # define PANGO_DEPRECATED_IN_1_8                PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_8_FOR(f)         PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_8                _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_8_FOR(f)         _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_8
//TODO # define PANGO_AVAILABLE_IN_1_8                 PANGO_UNAVAILABLE(1, 8)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_8                 _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_10
//TODO # define PANGO_DEPRECATED_IN_1_10               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_10_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_10               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_10_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_10
//TODO # define PANGO_AVAILABLE_IN_1_10                PANGO_UNAVAILABLE(1, 10)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_10                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_12
//TODO # define PANGO_AVAILABLE_IN_1_12                PANGO_UNAVAILABLE(1, 12)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_12                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_12
//TODO # define PANGO_DEPRECATED_IN_1_12               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_12_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_12               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_12_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_14
//TODO # define PANGO_AVAILABLE_IN_1_14                PANGO_UNAVAILABLE(1, 14)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_14                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_14
//TODO # define PANGO_DEPRECATED_IN_1_14               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_14_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_14               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_14_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_16
//TODO # define PANGO_AVAILABLE_IN_1_16                PANGO_UNAVAILABLE(1, 16)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_16                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_16
//TODO # define PANGO_DEPRECATED_IN_1_16               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_16_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_16               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_16_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_18
//TODO # define PANGO_DEPRECATED_IN_1_18               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_18_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_18               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_18_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_18
//TODO # define PANGO_AVAILABLE_IN_1_18                PANGO_UNAVAILABLE(1, 18)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_18                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_20
//TODO # define PANGO_DEPRECATED_IN_1_20               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_20_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_20               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_20_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_20
//TODO # define PANGO_AVAILABLE_IN_1_20                PANGO_UNAVAILABLE(1, 20)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_20                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_22
//TODO # define PANGO_DEPRECATED_IN_1_22               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_22_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_22               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_22_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_22
//TODO # define PANGO_AVAILABLE_IN_1_22                PANGO_UNAVAILABLE(1, 22)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_22                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_24
//TODO # define PANGO_DEPRECATED_IN_1_24               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_24_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_24               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_24_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_24
//TODO # define PANGO_AVAILABLE_IN_1_24                PANGO_UNAVAILABLE(1, 24)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_24                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_26
//TODO # define PANGO_DEPRECATED_IN_1_26               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_26_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_26               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_26_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_26
//TODO # define PANGO_AVAILABLE_IN_1_26                PANGO_UNAVAILABLE(1, 26)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_26                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_28
//TODO # define PANGO_DEPRECATED_IN_1_28               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_28_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_28               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_28_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_28
//TODO # define PANGO_AVAILABLE_IN_1_28                PANGO_UNAVAILABLE(1, 28)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_28                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_30
//TODO # define PANGO_DEPRECATED_IN_1_30               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_30_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_30               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_30_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_30
//TODO # define PANGO_AVAILABLE_IN_1_30                PANGO_UNAVAILABLE(1, 30)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_30                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_32
//TODO # define PANGO_DEPRECATED_IN_1_32               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_32_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_32               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_32_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_32
//TODO # define PANGO_AVAILABLE_IN_1_32                PANGO_UNAVAILABLE(1, 32)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_32                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_34
//TODO # define PANGO_DEPRECATED_IN_1_34               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_34_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_34               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_34_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_34
//TODO # define PANGO_AVAILABLE_IN_1_34                PANGO_UNAVAILABLE(1, 34)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_34                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_36
//TODO # define PANGO_DEPRECATED_IN_1_36               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_36_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_36               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_36_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_36
//TODO # define PANGO_AVAILABLE_IN_1_36                PANGO_UNAVAILABLE(1, 36)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_36                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_38
//TODO # define PANGO_DEPRECATED_IN_1_38               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_38_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_38               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_38_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_38
//TODO # define PANGO_AVAILABLE_IN_1_38                PANGO_UNAVAILABLE(1, 38)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_38                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_40
//TODO # define PANGO_DEPRECATED_IN_1_40               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_40_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_40               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_40_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_40
//TODO # define PANGO_AVAILABLE_IN_1_40                PANGO_UNAVAILABLE(1, 40)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_40                _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MIN_REQUIRED >= PANGO_VERSION_1_42
//TODO # define PANGO_DEPRECATED_IN_1_42               PANGO_DEPRECATED
//TODO # define PANGO_DEPRECATED_IN_1_42_FOR(f)        PANGO_DEPRECATED_FOR(f)
//TODO #else
//TODO # define PANGO_DEPRECATED_IN_1_42               _PANGO_EXTERN
//TODO # define PANGO_DEPRECATED_IN_1_42_FOR(f)        _PANGO_EXTERN
//TODO #endif

//TODO #if PANGO_VERSION_MAX_ALLOWED < PANGO_VERSION_1_42
//TODO # define PANGO_AVAILABLE_IN_1_42                PANGO_UNAVAILABLE(1, 42)
//TODO #else
//TODO # define PANGO_AVAILABLE_IN_1_42                _PANGO_EXTERN
//TODO #endif

// #endif (* __PANGO_VERSION_H__ *)
